Add mint and burn to balances-adapter
ReDeFi-Blockchain/redefi-parachain pull request #14
Opened 2024-06-19 10:50 UTC by vklachkov

2024-06-20 05:28 UTC, PraetorP commented on pallets/balances-adapter/src/eth.rs
> +		Err(dispatch_to_evm::<T>(
Это заглушка ? @uandysmith, нам же не надо устанавливать пермишны через EVM ?

2024-06-20 05:33 UTC, PraetorP commented on pallets/balances-adapter/src/lib.rs
> +	bitflags::bitflags! {
Переложи, пожалуйста, в другое место. Вроде не встречал , чтобы объявление подобных структур было примерно в  подобном месте(между стореджами и конфигом). Обычно в модуле паллеты идут хранилища, конфиг, имплементация паллеты.

2024-06-20 05:36 UTC, PraetorP commented on pallets/balances-adapter/src/lib.rs
> +		StorageMap<_, Blake2_128, T::CrossAccountId, AccountPermissions, ValueQuery>;
Изменить ключь на адрес(H160). Там где подразумевается взамодействие из субстрата можно брать эфирное зеркало.

2024-06-20 05:41 UTC, PraetorP commented on pallets/balances-adapter/src/lib.rs
> +		pub(crate) fn burn_unchecked(account: &T::CrossAccountId, amount: u128) -> DispatchResult {
Зачем тут Кросс ? Ты ниже по коду используешь `as_eth()`. Используй кросс только там, где это действительно необходимо(например, если напрямую передаешь что то паллете балансов). также по остальному коду.

2024-06-20 05:41 UTC, vklachkov commented on pallets/balances-adapter/src/eth.rs
> +		Err(dispatch_to_evm::<T>(
Да, это заглушка. Для совместимости с evm-assets. Насколько я понял из вчерашнего обсуждения, нет, нам не треба выставлять права через EVM

2024-06-20 05:51 UTC, PraetorP commented on pallets/balances-adapter/src/eth.rs
> +		Err(dispatch_to_evm::<T>(
Ну он бы тебе всеравно вернул ошибку селектора. Если уж и делать тут нечто подобное, то возвращать что то нападобие `Unsupported`.

2024-06-20 05:54 UTC, PraetorP commented on pallets/balances-adapter/src/lib.rs
> +		pub fn set_account_permissions(
Как ты планируешь вызывать этот метод в субстрате ?

2024-06-20 08:12 UTC, PraetorP commented on pallets/balances-adapter/src/lib.rs
> +			Self::mint_into(to.as_eth(), amount.into())?;
Может лучше сразу это и возвращать вместо `Ok(())` ? В других местах также

2024-06-20 08:24 UTC, uandysmith requested changes

2024-06-20 08:24 UTC, uandysmith commented on pallets/balances-adapter/src/eth.rs
> +		Err(dispatch_to_evm::<T>(
Наоборот, вчера решили что все выставление прав будет только через evm

2024-06-21 11:11 UTC, PraetorP commented on pallets/balances-adapter/src/lib.rs
> +			Ok(())
Уже писал об этом ( возможно оно сползло). Зачем тут Ok(())? Строка выше уже возвращает `DispatchResult`. В других местах тоже исправь, пожалуйста.

2024-06-21 11:14 UTC, PraetorP commented on pallets/balances-adapter/src/lib.rs
> +		type SudoAccountId: for<'a> TryFrom<&'a [u8]> + Into<Self::AccountId>;
Зачем дполнительный ассоциированный тип , если по сути он `Self::AccountId` ?

2024-06-21 11:30 UTC, PraetorP commented on pallets/balances-adapter/src/lib.rs
> +			Ok(())
Upd: Посмотрел там он возвращает баланс. В целом тогда править наверное не надо.

2024-06-21 11:31 UTC, PraetorP commented on pallets/balances-adapter/src/lib.rs
> +			Ok(())
Я в подобных случаях пишу нечто подобное: 
```
Self::mint_into(to, amount.into())
				.map(|_| ())
				.map_err(Self::map_substrate_error)
```

2024-06-21 11:41 UTC, vklachkov commented on pallets/balances-adapter/src/lib.rs
> +			Ok(())
Метод `mint_into`, как и `burn_from` из трейта `Mutate` возвращают `Result<Self::Balance, DispatchError>`.

![image](https://github.com/ReDeFi-Blockchain/redefi-parachain/assets/60278551/c0b069aa-7782-44a0-b6b7-134e5b89dbc5)

2024-06-21 11:47 UTC, PraetorP commented on pallets/balances-adapter/src/lib.rs
> +			Ok(())
> Метод mint_into, как и burn_from из трейта Mutate возвращают Result<Self::Balance, DispatchError>.

В [сообщении](https://github.com/ReDeFi-Blockchain/redefi-parachain/pull/14#discussion_r1648841356) говорю об этом же.

2024-06-21 12:01 UTC, vklachkov commented on pallets/balances-adapter/src/lib.rs
> +			Ok(())
У меня почему-то гитхаб подгружает твои комментарии с задержкой. Спасибо за комментарий! Я тоже думал сделать map на (), но решил оставить Ok(()).

2024-06-21 12:34 UTC, vklachkov commented on pallets/balances-adapter/src/lib.rs
> +		type SudoAccountId: for<'a> TryFrom<&'a [u8]> + Into<Self::AccountId>;
AccountId не реализует `TryFrom<&[u8]>`, а в Rust, насколько я знаю, нельзя переопределить ассоциированный тип или дополнить его. В качестве обходного решения, добавил новый тип.

Если есть идея лучше, напиши, пожалуйста.

2024-06-21 13:46 UTC, vklachkov commented on pallets/balances-adapter/src/eth.rs
> +		let account = T::CrossAccountId::from_eth(account);
У нас в паллете было очень много ненужных конвертаций. Я поудалял часть около новых методов, чтобы не рефакторить всю паллету в этом PR.

2024-06-22 05:39 UTC, vklachkov commented on pallets/balances-adapter/src/lib.rs
> +		type SudoAccountId: for<'a> TryFrom<&'a [u8]> + Into<Self::AccountId>;
С версии 1.79, оказывается, [можно](https://blog.rust-lang.org/2024/06/13/Rust-1.79.0.html#bounds-in-associated-type-position). Удалил дополнительный тип в коммите 464fa09bd2ad94ef2814bea9f22a5ffd3bb4da04.

2024-06-24 08:50 UTC, PraetorP approved these changes

2024-06-24 08:58 UTC, uandysmith approved these changes

2024-06-24 10:07 UTC, merged