impl fungibles,  mint& burn support
ReDeFi-Blockchain/redefi-parachain pull request #6
Opened 2024-05-15 05:57 UTC by PraetorP

2024-05-29 20:50 UTC, mrshiposha requested changes

2024-05-29 20:50 UTC, mrshiposha commented on pallets/evm-assets/src/impl_fungibles.rs
> +	fn decrease_balance(
`decrease_balance` и `increase_balance` выглядят неправильно, ибо никак не влияют на total_issuance.
По-хорошему, вместо `<Balances<T>>::set` они должны обращаться соот-но к `Self::burn` и `Self::mint`

2024-05-29 20:50 UTC, mrshiposha commented on pallets/evm-assets/src/impl_fungibles.rs
> +		<Pallet<T>>::mint(&asset, who, amount).map(|_| amount)
По идее, тут надо вызывать `increase_balance` и передавать `precision`. Тоже самое для burn_from.

2024-05-29 20:50 UTC, mrshiposha commented on pallets/evm-assets/src/xcm.rs
> +		if *parents != 1 {
Неверно для реле. Для реле parents == 0

2024-05-29 20:50 UTC, mrshiposha commented on pallets/evm-assets/src/xcm.rs
> +			network: _,
Возможно bridge'ы потом, не знаю как этот параметр могут задействовать. Лучше сматчить None напрямую.

2024-05-29 20:50 UTC, mrshiposha commented on runtime/common/config/xcm.rs
> +	// TODO
?

2024-05-30 04:59 UTC, PraetorP commented on pallets/evm-assets/src/xcm.rs
> +			network: _,
В адаптере у нас `network: Network::get()`

2024-05-30 07:40 UTC, PraetorP commented on runtime/common/config/xcm.rs
> +	// TODO
Забыл убрать.

2024-05-30 17:47 UTC, mrshiposha requested changes

2024-05-30 17:47 UTC, mrshiposha commented on pallets/evm-assets/src/impl_fungibles.rs
> +			Precision::Exact,
Не хочется здесь игнорировать параметры `precision` и `force`. Если уж и игорировать их (в чем я сомневаюсь, см. коммент выше), то в самом конце вызовов

2024-05-30 17:47 UTC, mrshiposha commented on pallets/evm-assets/src/xcm.rs
> +		let relay_parent = match T::UniversalLocation::get().global_consensus() {
`UniversalConsensus` **всегда** включает в себя первым junction'ом `GlobalConsensus`.
* На реле это будет `GlobalConsensus(NetworkId)`
* На парачейне это будет `GlobalConsensus(RelayNetworkId)/Parachain(ParaId)`

Так как функция `global_consensus` возвращает первый junsion, просто игнорируя остальные, тут всегда будет `relay_parent == 0`, что неверно для парачейна

2024-05-30 17:48 UTC, mrshiposha commented
@uandysmith по какой-то причине все мои комменты на ревью тут нельзя резолвить (кнопки нет). Мб что-то в настройках репозитория или я недобавлен в проект?

2024-05-30 18:37 UTC, CertainLach commented on pallets/evm-assets/src/impl_fungibles.rs
> +		let new_balance = if let BestEffort = precision {
match с одной веткой не нравится clippy часто, что порой раздражает)

2024-05-31 04:43 UTC, PraetorP commented on runtime/common/config/xcm.rs
> +	// We don't track any teleports.
Там сделано аналогично.  Или ты про другое ?
https://github.com/polkadot-fellows/runtimes/blob/aabf6dbda84d1da498d211942e4245695dfb7020/system-parachains/asset-hubs/asset-hub-polkadot/src/xcm_config.rs#L121

2024-05-31 08:00 UTC, mrshiposha commented on runtime/common/config/xcm.rs
> +	// We don't track any teleports.
Надо с этим повнимательнее разобраться. Для нативной валюты (DOT) AssetHub действительно делает так же.
А вот для других [добавляет проверки](https://github.com/polkadot-fellows/runtimes/blob/aabf6dbda84d1da498d211942e4245695dfb7020/system-parachains/asset-hubs/asset-hub-polkadot/src/xcm_config.rs#L143).

Не знаю, как нам лучше сделать. Я с этой частью XCM не подробно знаком. Я бы предложил узнать зачем это может быть нужно для телепортов и оценить насколько это нужно для Redefi

2024-06-03 12:14 UTC, mrshiposha requested changes

2024-06-03 12:14 UTC, mrshiposha commented on pallets/evm-assets/src/impl_fungibles.rs
> +		_precision: frame_support::traits::tokens::Precision,
А можно сюда такой же коммент, как и в `decrease_balance`?)
Или просто сказать, что "см. причину игнора параметра в комментарии `decrease_balance`"

2024-06-03 12:14 UTC, mrshiposha commented on pallets/evm-assets/src/impl_fungibles.rs
> +		_preservation: frame_support::traits::tokens::Preservation,
Тоже, либо ссылку на коммент к `decrease_balance`, либо прямо тут бы сказать почему мы игнорим это

2024-06-03 14:33 UTC, CertainLach commented on runtime/redefi/src/lib.rs
> +	hex_literal::hex!("c54305bb26444b69a3f948914a75f77f6c0510af4f2cee2feab9943792ddf789");
Лучше уточнить у @mrshiposha как тут лучше поступить с ID сети, я не уверен что вы можете его просто так сменить, возможно он где-то в хранилищах осел (Однако могу по требованию собрать список хранилищ, что NetworkId в себе содержат)

2024-06-03 14:39 UTC, mrshiposha commented on runtime/redefi/src/lib.rs
> +	hex_literal::hex!("c54305bb26444b69a3f948914a75f77f6c0510af4f2cee2feab9943792ddf789");
Если что-то касается XCM — это никак не должно влиять. Однако, я тоже не уверен, что он где-нибудь ещё в рантайма не сидит

2024-06-03 14:41 UTC, CertainLach commented on runtime/redefi/src/lib.rs
> +	hex_literal::hex!("c54305bb26444b69a3f948914a75f77f6c0510af4f2cee2feab9943792ddf789");
Может вам Ethereum(X) использовать, или добавить и попробовать заапстримить Private([u8; 8]) для приватных чейнов?)

2024-06-03 14:43 UTC, CertainLach commented on runtime/redefi/src/lib.rs
> +	hex_literal::hex!("c54305bb26444b69a3f948914a75f77f6c0510af4f2cee2feab9943792ddf789");
У реле и так будет идентификатор эфирной сети)

2024-06-03 14:44 UTC, CertainLach commented on runtime/redefi/src/lib.rs
> +	hex_literal::hex!("c54305bb26444b69a3f948914a75f77f6c0510af4f2cee2feab9943792ddf789");
`Custom([u8; 8])` скоре всего к bikesheeding приведёт, поэтому `Private`

2024-06-03 14:45 UTC, mrshiposha commented on runtime/redefi/src/lib.rs
> +	hex_literal::hex!("c54305bb26444b69a3f948914a75f77f6c0510af4f2cee2feab9943792ddf789");
Это так же грязно, как и указывать NetworkId::Polkadot там, где на самом деле не полька. ByGenesis — лишь идентифицирует экосистему. А ID экосистемы Redefi — это продовый генезис хеш (это соглашение легко ввести).

Ethereum можно, коли там есть chain_id, но это ИМХО не совсем честно

2024-06-03 14:47 UTC, CertainLach commented on runtime/redefi/src/lib.rs
> +	hex_literal::hex!("c54305bb26444b69a3f948914a75f77f6c0510af4f2cee2feab9943792ddf789");
Я понимаю, но тут именно тот факт что реле в качестве его id сети будет ByGenesis... Мне очень не нравится)

2024-06-03 14:48 UTC, CertainLach commented on runtime/redefi/src/lib.rs
> +	hex_literal::hex!("c54305bb26444b69a3f948914a75f77f6c0510af4f2cee2feab9943792ddf789");
Ethereum с chain_id будет и короче, и красивее, chain_id то redefi будет присвоен

2024-06-03 14:52 UTC, mrshiposha commented on runtime/redefi/src/lib.rs
> +	hex_literal::hex!("c54305bb26444b69a3f948914a75f77f6c0510af4f2cee2feab9943792ddf789");
Они уже вроде какой-то конкретный chain_id хотят. Вроде мы его уже где-то выставили

2024-06-03 14:52 UTC, mrshiposha commented on runtime/redefi/src/lib.rs
> +	hex_literal::hex!("c54305bb26444b69a3f948914a75f77f6c0510af4f2cee2feab9943792ddf789");
Да, пускай будет так. Он действительно сильно эфирный Чейн с эфирными аккаунта и со своим chain_id

2024-06-04 04:18 UTC, PraetorP commented on runtime/redefi/src/lib.rs
> +	hex_literal::hex!("c54305bb26444b69a3f948914a75f77f6c0510af4f2cee2feab9943792ddf789");
У нас разный чейн айди для тестнета и продакшн. В универсал локейшн будем это учитывать ?

2024-06-04 08:21 UTC, mrshiposha commented on runtime/redefi/src/lib.rs
> +	hex_literal::hex!("c54305bb26444b69a3f948914a75f77f6c0510af4f2cee2feab9943792ddf789");
>У нас разный чейн айди для тестнета и продакшн. В универсал локейшн будем это учитывать ?

Да, давай учитывать. По аналогии с Юник/Кварц/Опал, у которых NetworkId Polkadot/Kusama/Westend соответственно

2024-06-04 09:05 UTC, mrshiposha approved these changes

2024-06-04 09:55 UTC, merged